// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPBzkSKOdFT7LKac-O5442FiBHExC6g2k',
    appId: '1:136689718974:android:0c621d9059fb480e7e30ef',
    messagingSenderId: '136689718974',
    projectId: 'al-mamin',
    storageBucket: 'al-mamin.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBF7cCXiXX6pDlP4FdhmDco0KhiWIvVw8',
    appId: '1:136689718974:web:e7a5cfba85e56d8b7e30ef',
    messagingSenderId: '136689718974',
    projectId: 'al-mamin',
    authDomain: 'al-mamin.firebaseapp.com',
    storageBucket: 'al-mamin.firebasestorage.app',
    measurementId: 'G-M92T791VLY',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBF7cCXiXX6pDlP4FdhmDco0KhiWIvVw8',
    appId: '1:136689718974:web:e7a5cfba85e56d8b7e30ef',
    messagingSenderId: '136689718974',
    projectId: 'al-mamin',
    authDomain: 'al-mamin.firebaseapp.com',
    storageBucket: 'al-mamin.firebasestorage.app',
    measurementId: 'G-M92T791VLY',
  );
}
